
---
- hosts: localhost
  


  tasks: 
         - name: Install a Package
           yum: name: httpd  state: present


         - name: Start httpd service
           service: name=httpd status=started
